backend:
  name: github
  repo: merturl/blog
  local_backend: true

media_folder: blog/images
public_folder: ./images

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    nested: { depth: 100 }
    media_folder: ""
    public_folder: ""
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list }
      - { name: thumbnail, label: Thumbnail, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
    meta: { path: { widget: string, label: "Path", index_file: "index" } }
