backend:
  name: github
  branch: master
  repo: merturl/blog
local_backend: true
publish_mode: editorial_workflow
media_folder: blog/images
public_folder: ./images

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    nested: { depth: 100 }
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list }
      - {
          name: thumbnail,
          label: Thumbnail,
          widget: image,
          required: true,
          media_folder: "images",
        }
      - { name: body, label: Body, widget: markdown }
